routes/web.php
<?php

use App\Http\Controllers\AuthLoginController;
use App\Http\Controllers\ChatController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AuthLoginController::class, 'showLoginForm']);
Route::post('/login', [AuthLoginController::class, 'login'])->name('login');
Route::post('/logout', [AuthLoginController::class, 'logout'])->name('logout');

Route::middleware('auth')->group(function () {
    Route::prefix('chat')->name('chat.')->group(function () {
        Route::get('/', [ChatController::class, 'index'])->name('index');
        Route::get('/load/{groupId}', [ChatController::class, 'loadMessage'])->name('load');
        Route::post('/send', [ChatController::class, 'sendMessage'])->name('send');
    });
});

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Group extends Model
{
    use HasFactory;

    protected $fillable = ['name'];

    public function members(): HasMany
    {
        return $this->hasMany(GroupMember::class, 'group_id');
    }
}

app/Models/GroupMember.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class GroupMember extends Model
{
    use HasFactory;

    protected $fillable = ['group_id', 'user_id'];
}

app/Models/GroupMessage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class GroupMessage extends Model
{
    use HasFactory;

    protected $fillable = ['group_id', 'user_id', 'message'];
    protected $appends = ['sent_at'];

    public function group(): BelongsTo
    {
        return $this->belongsTo(Group::class, 'group_id');
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getSentAtAttribute() {
        return date('d-m-Y H:i', strtotime($this->created_at));
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function canJoinRoom($groupId) {
        $group = Group::findOrFail($groupId);
        foreach ($group->members as $member) {
            if ($this->id == $member->user_id ) {
                return true;
            }
        }

        return false;
    }
}

app/Http/Controllers/AuthLoginController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthLoginController extends Controller
{
    public function showLoginForm() {
        return view('auth.login');
    }

    public function login(Request $request) {
        if (Auth::attempt(['email' => $request->email, 'password' => $request->password])) {
            return redirect()->route('chat.index');
        }

        return redirect()->back()->with('email atau password salah');
    }
}

app/Http/Controllers/ChatController.php
<?php

namespace App\Http\Controllers;

use App\Events\SendMessage;
use App\Models\Group;
use App\Models\GroupMessage;
use Illuminate\Http\Request;

class ChatController extends Controller
{
    public function index() {
        $data['groups'] = Group::all();

        return view('pages.chat', $data);
    }

    public function sendMessage(Request $request) {
        $groupId = $request->group_id;
        $userId = auth()->user()->id;
        $message = $request->message;
        $groupMessage = GroupMessage::create([
            'group_id' => $groupId,
            'user_id' => $userId,
            'message' => $message,
        ]);
        
        broadcast(new SendMessage($groupMessage->user()->associate(auth()->user())));

        return response()->json([
            'success' => true,
            'message' => "success"
        ]);
    }

    public function loadMessage($groupId) {
        $messages = GroupMessage::with(['group', 'user'])->where('group_id', $groupId)->orderBy('created_at', 'asc')->get();

        return response()->json([
            'success' => true,
            'data' => $messages
        ]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/layouts/app.blade.php
<!-- resources/views/layouts/app.blade.php -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <link href="{{ asset('css/app.scss') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>
<body>
    <header>
    </header>

    <main>
        <div class="mt-4">
            @yield('content')
        </div>
    </main>

    <footer>

    </footer>

    <script src="{{ asset('js/app.js') }}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    @yield('js')
</body>
</html>

resources/views/pages/chat.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .sender-message {
            background-color: #dcf8c6;
            padding: 10px;
            border-radius: 10px;
            margin-bottom: 10px;
            text-align: left;
            margin-right: 80px;
        }

        .receiver-message {
            background-color: #f1f0f0;
            padding: 10px;
            border-radius: 10px;
            margin-bottom: 10px;
            text-align: right;
            margin-left: 80px;
            margin-right: 10px;
        }

        .sender-name {
            font-weight: bold;
        }

        .message-text {
            margin-top: 5px;
        }

        .time-text {
            margin-top: 5px;
            font-size: 11px;;
        }

    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        Groups
                    </div>
                    <div class="card-body">
                        <ul class="list-group contact-list">
                            @foreach($groups as $group)
                                <a href="#" class="group" data-group-id="{{$group->id}}" data-group-name="{{$group->name}}">
                                    <li class="list-group-item">
                                        <div class="group-name">{{$group->name}}</div>
                                    </li>
                                </a>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <span id="chat-group-name"></span>
                    </div>
                    <div class="card-body">
                        <ul class="chat-messages" id="chat-messages" style="height: 50vh; overflow-y: scroll;">
                            <!-- list chat -->
                        </ul>
                    </div>
                    <div class="card-footer">
                        <div class="input-group">
                            <input type="text" class="form-control" id="chat-message-input" placeholder="Type your message..." disabled>
                            <input type="hidden" id="chat-group-input" value="">
                            <div class="input-group-append">
                                <button class="btn btn-primary" id="chat-send-button" disabled>Send</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        $(document).ready(function () {
            const Echo = window.Echo
            var input = document.getElementById('chat-message-input')
            

            input.addEventListener('keypress', function(event) {
                if (event.key === 'Enter') {
                    event.preventDefault();
                    $('#chat-send-button').trigger('click')
                    $('#chat-message-input').val('')
                }
            })

            $('.group').click(function(){
                var groupName = $(this).attr('data-group-name')
                var groupId = $(this).attr('data-group-id')
                channelListener(groupId)

                $('#chat-group-name').text(groupName)
                $('#chat-group-input').val(groupId)

                $('.list-group-item').removeClass('active')
                var item = $(this).find('.list-group-item')
                $(item).addClass('active')

                $('#chat-message-input').prop('disabled', false)
                $('#chat-send-button').prop('disabled', false)

                $('#chat-messages').empty()
                var ajaxurl = "{{route('chat.load', ':groupId')}}";
                ajaxurl = ajaxurl.replace(':groupId', groupId);
                $.ajax({
                    url: ajaxurl,
                    method: 'GET',
                    success: function(response) {
                        var data = response.data
                        var userId = '{!! Auth::user()->id !!}'
                        $.each(data, function(key, value){
                            if(value.user_id == userId) {
                                $('#chat-messages').append(`
                                    <div class="message">
                                        <div class="receiver-message">
                                            <p class="message-text">`+value.message+`</p>
                                            <p class="time-text">`+value.sent_at+`</p>
                                        </div>
                                    </div>
                                `)
                            } else {
                                $('#chat-messages').append(`
                                    <div class="sender-message">
                                        <p class="sender-name">`+value.user.name+`</p>
                                        <p class="message-text">`+value.message+`</p>
                                        <p class="time-text">`+value.sent_at+`</p>
                                    </div>
                                `)
                            }
                        })

                        var messageContainer = document.getElementById('chat-messages');
                        messageContainer.scrollTo(0, messageContainer.scrollHeight);
                    },
                    error: function(xhr, status, error) {
                        console.log(error);
                    }
                });
                
            })

            $('#chat-send-button').click(function(){
                var ajaxurl = "{{route('chat.send')}}";
                var message = $('#chat-message-input').val()
                var groupId = $('#chat-group-input').val()
                if (groupId) {
                    $.ajax({
                        url: ajaxurl,
                        method: 'POST',
                        data: {
                            _token: '{{ csrf_token() }}',
                            group_id: groupId,
                            message: message
                        },
                        success: function(response) {
                            
                        },
                        error: function(xhr, status, error) {
                            console.log(error);
                        }
                    });
                }
            })

           

            function channelListener(groupId) {
                if (groupId) {
                    Echo.leave('chat.'+groupId)
                    
                    let channel = Echo.join('chat.'+groupId)
                    var userId = '{!! Auth::user()->id !!}'
                    channel.listen('SendMessage', function(data){
                        var groupMessage = data.groupMessage
                        if(groupMessage.user_id == userId) {
                            $('#chat-messages').append(`
                                <div class="message">
                                    <div class="receiver-message">
                                        <p class="message-text">`+groupMessage.message+`</p>
                                        <p class="time-text">`+groupMessage.sent_at+`</p>
                                    </div>
                                </div>
                            `)
                        } else {
                            $('#chat-messages').append(`
                                <div class="sender-message">
                                    <p class="sender-name">`+groupMessage.user.name+`</p>
                                    <p class="message-text">`+groupMessage.message+`</p>
                                    <p class="time-text">`+groupMessage.sent_at+`</p>
                                </div>
                            `)
                        }
                    })
                }
            }

            var groupId = $('#chat-group-input').val()
            channelListener(groupId)
        });
    </script>
@endsection